### PR TITLE
Added to the story

### PR DESCRIPTION
**Pull request by poppywis3**

### CODE REVIEW

**Comment by jimmylorunning** [comment]
Hi Jen! index.php has changed since you last forked it. Please fetch it again and take a look at the changes. I think the change you want to make will be in homepage.html instead. Let me know if you need any help!

**Comment by poppywis3** [comment]
Ah ok thank you for your patience! I saw the burrito and everything but was confused when I just cloned it today...until I realized I cloned the one I had forked a while ago. Doh! Thanks will try again and will do homepage.html instead. Thanks Jimmy!

**Comment by poppywis3** [comment]
I went to fork the repo again, but 'homepage.html' is still not showing up in my repo. Do you know why this is? It still looks like the one I forked originally.

**Comment by jimmylorunning** [comment]
I'm not sure, but this might be what you're trying to do: https://help.github.com/articles/syncing-a-fork/

Basically the forks are out of sync. You want your fork to look like the new origin.

**Comment by poppywis3** [comment]
Thanks! I am giving it a go, but am having some conflicts but I will try to sort it out later. Thanks for the help!

**Pull request closed without merging**
