### PR TITLE
add a page about Jimmy Lo and a header link to that page

### PR DESCRIPTION
**Pull request by jastuccio**
I do not have a local php server right now and was not able to test my changes before making this pull request.

### CODE REVIEW

**Comment by jimmylorunning** [comment]
Looks great! I think I'm more comfortable with my credits being in the footer than the header, though. I'm going to make a commit to your branch and push it back up to github... (this is my first time receiving a pull request and making a change to it so excuse me if this doesn't work!)

**Comment by jimmylorunning** [comment]
Hmm weird... I pushed it back to github but it's not showing in this pull request history...

**Comment by jimmylorunning** [comment]
So I think I can't make changes to the request... I can only ask you to change it... Can you move the link out of the header and put it in the footer? You can add it at the end like so "Created by Jimmy Lo."

**Comment by jastuccio** [comment]
I moved the link into the footer.  Is that more what you had in mind?

**Comment by jimmylorunning** [comment]
Yes, thank you!

**Pull request merged**
